### ISSUE TITLE
Template should use externalised strings

### ISSUE THREAD

**Issue by alanocallaghan** [qupath/qupath-extension-template#11]
If we're considering this to be best practice, it should probably be the default in extensions

**Comment by petebankhead** [comment]
Yes, tentatively.

I remain a bit unclear on how we can actually support different languages with externalized strings across the main app - never mind extensions. I thought 'localization extensions' could be a thing: we'd have a custom controller that could add language support for the entire app via a custom extension. But now I see that we have a huge number of strings, and also `ResourceBundles` operate quite differently in modularized apps - so now I don't know.

I was also pondering today if we should embed more documentation within our app code, so it can be embedded in the app and automatically extracted for the website. We currently have this: https://qupath.readthedocs.io/en/0.5/docs/reference/commands.html
It uses the menus and tooltips to generate a page, but perhaps we could/should have longer descriptions embedded. The relevance is that this could potentially also be localizable. If so, I don't know how we handle that in terms of property files (lots of small ones, or fewer huge ones).

I'm not entirely sure how they do it, but to me the CellProfiler docs seem spectacularly good. You can get them [by version](https://cellprofiler.org/manuals), and there is standardized, detailed info for each command: https://cellprofiler-manual.s3.amazonaws.com/CellProfiler-4.2.6/modules/measurement.html

I feel the separation between our code and our docs is making it harder to ensure we're consistent, and maybe we need a better policy for strings in general.

**Comment by alanocallaghan** [comment]
If not for localisation, I at least like that externalised strings give you a single place to change every UI label/tooltip/etc

Agree about the code + docs combo, generally documenting code is easier (and less likely to drift). The CellProfiler docs are indeed excellent, I might investigate their build system
