### ISSUE TITLE
Template fails to build

### ISSUE THREAD

**Issue by alanocallaghan** [qupath/qupath-extension-template#5]
Steps to reproduce:

1. Generate repo from template
2. run `./gradlew build`

Result:
```
> Task :compileGroovy
> Task :processResources
> Task :classes
> Task :jar
> Task :javadoc FAILED
5 actionable tasks: 5 executed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':javadoc'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '[...]/qupath-extension-test/build/tmp/javadoc/javadoc.options'
```

Small possibly useless extra tidbit provided by IntelliJ:
```
Cause: error=2, No such file or directory
```
...but I've tried looking at extra debug info to no avail

**Comment by petebankhead** [comment]
Hmmm, builds for me but with a complaint.
PR now with an attempted fix (which also gets rid of the complaint).

**Comment by alanocallaghan** [comment]
If it's only my machine then I'll dig into it properly tomorrow

**Comment by petebankhead** [comment]
Have you checked the generated javadoc options file for clues?

I've seen small javadoc errors kill a build, but the default is to kindly ask the javadoc to not be so petty: https://github.com/qupath/qupath-extension-template/blob/main/build.gradle#L99

**Comment by alanocallaghan** [comment]
I can't spot anything obvious, all of the listed directories exist and the other options all seem sensible too

**Comment by petebankhead** [comment]
Does it build successfully if you comment on the line `withJavadocJar()` ?
(I guess you've also tried `gradlew clean`)

**Comment by alanocallaghan** [comment]
Hadn't tried clean as I was working from a fresh clone, but it doesn't change anything. Removing `withJavadocJar` does allow me to build, yeah

**Comment by alanocallaghan** [comment]
Ah!  It's trying to run `/usr/lib/jvm/java-11-openjdk-amd64/bin/javadoc` but
`ls: cannot access '/usr/lib/jvm/java-11-openjdk-amd64/bin/javadoc': No such file or directory`

Just a jdk config error by me

**Comment by petebankhead** [comment]
Hmmm, not an entirely satisfying solution though... only other thing i can think of is that you've got an unhappy JDK. Throwing 
```groovy
println System.properties['java.home']
```
into `build.gradle` should print whatever it's using. The easiest way to change is often to create a `gradle.properties` file and include (at least)
```groovy
org.gradle.java.home=/path/to/jdk/
```
You can technically run Gradle with one JDK but build with another, thanks to [toolchains](https://docs.gradle.org/current/userguide/toolchains.html) - so conceivably the toolchain is hunting for some unexpected JDK to use.

I generally use the builds from Eclipse Temurin™ and that's also what is used with GitHub Actions here.

**Comment by alanocallaghan** [comment]
It's poor exception handling from gradle for sure, the issue is I have `openjdk-11-jdk` installed (and maybe some other packages) but not `openjdk11-doc`
